<a href="https://colab.research.google.com/github/kabilan942/TensorFlow/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.8.2


### Creating tensors with `tf.constant`

In [ ]:
# Creating tensors with tf.constant
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

`ndim` looks out for number of elements in the shape attribute

In [ ]:
# Checking the number of dimension of a tensor
# ndim - number of dimensions

scaler.ndim

0

In [ ]:
# Creating a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Checking dimensions of the vector

vector.ndim

1

In [ ]:
# Creating a matrix (matrix has more than 1 dimension)

matrix = tf.constant([[10, 7], [5, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  4]], dtype=int32)>

In [ ]:
# Checking dimensions of the matrix

matrix.ndim

2

In [ ]:
# dtype=int32 is default unless specified otherwise
# has a 32 bit precision; which is more accurate and takes 
# more space storing the values than what a 16 bit precision 
# such as dtye=float16 will take.

# Creating another matrix

matrix_1 = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
matrix_1.ndim

2

In [ ]:
# Creating a tensor

tensor = tf.constant([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8]]], dtype=int32)>

In [ ]:
tensor.ndim

3

0-dimensional scaler, 1-dim vector, 2-dim matrix are all generally called **tensor**

Tensor is a n-dimensional array of numbers (n - any number)

### Creating tensors with `tf.Variable` 

In [ ]:
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [ ]:
# using .assign() to change value in changeable_tensor

changeable_tensor.assign([7,2])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

Unlike changeable_tensor, unchangeable_tensor created using `tf.constant()` cannot be manipulated once created

### Creating Random Tensors

When choosing the weights for the neural layes, initially a random sets of weights are initialized and then based on furhter examples these weights are optimized.

THese random weights can be initialized using the random tensors.

In [ ]:
# creating 2 random (but same (by setting seed)) tensors

random_1 = tf.random.Generator.from_seed(7)  # setting seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

Valuable for when you want to shuffle your data so the inherent order doesn't learning

`tf.random.shuffle` : Randomly shuffles a tensor along its first dimension.





In [ ]:
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

We get different order each time the above cell is run.

TO get same result, set seed to a number

In [ ]:
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. 

`tf.random.set_seed()` : This sets the global seed
 
`tf.random.shuffle(not_shuffled, seed=7)` : Operational-level

### Other ways to make tensors 

* `tf.ones()`
* tf.zeros

In [ ]:
tf.ones(shape=(3,2,4))

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros((7,5))

<tf.Tensor: shape=(7, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Numpy arrays to Tensors

The main difference between a numpy array and a tensor is that tensor can be run on GPU (allows faster numerical computing)

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
tensor_A.ndim

1

In [ ]:
tensor_B = tf.constant(numpy_A, shape=(3,8))
tensor_B

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
tensor_B.ndim

2

In [ ]:
tensor_C = tf.constant(numpy_A, shape=(3,2,4))
tensor_C

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
tensor_C.ndim

3

### Getting information from Tensors

When dealing with tensors, we would want to know the following attributes:
* Shape : `tensor.shape` - Length of each of the dimensions of a tensor
* Rank : `tensor.ndim` - Number of tensor dimensions. Scaler has rank 0, vector has rank 1, matrix has rank 2, a tensor has rank n 
* Axis or dimension : `tensor[0]`, `tensor[ : ,1]` - a particular dimension of a tensor
* Size : `tf.size(tensor)` - Total number of items in a tensor

In [ ]:
# creating a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

# An array with 5 zeros initially
# 4 such arrays with 5 0's each
# 3 such arrays with each of the 3 array having 4 arrays with 5 0's each
# 2 arrays with each of the 2 having 3 arrays of the above type

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# accessing first of 2 of the outermost arrays
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print('Shape of rank_4_tensor:', rank_4_tensor.shape)
print('Number of elements along first axis:', rank_4_tensor.shape[0])
print('Number of elements along last (4th) axis:', rank_4_tensor.shape[-1])  # rank_4_tensor[3]
print('Number of dimensions [Rank] of rank_4_tensor:', rank_4_tensor.ndim)
print('Size of rank_4_tensor:', tf.size(rank_4_tensor))  # size = 2*3*4*5
print('Size of rank_4_tensor:', tf.size(rank_4_tensor).numpy())
print('Datatype of every element:', rank_4_tensor.dtype)

Shape of rank_4_tensor: (2, 3, 4, 5)
Number of elements along first axis: 2
Number of elements along last (4th) axis: 5
Number of dimensions [Rank] of rank_4_tensor: 4
Size of rank_4_tensor: tf.Tensor(120, shape=(), dtype=int32)
Size of rank_4_tensor: 120
Datatype of every element: <dtype: 'float32'>


### Indexing Tensors

Similar to python lists

In [ ]:
# Getting first 2 elements from each of the dimensions of rank_4_tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0,0,:,:3]

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
rank_2_tensor[:, 1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Adding a new dimension to an existing tensor

rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]   # also written as rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
rank_3_tensor.shape

TensorShape([2, 2, 1])

In [ ]:
rank_2_tensor[tf.newaxis, :, :, tf.newaxis]

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]],

        [[3],
         [4]]]], dtype=int32)>

## Manipulating Tensors (Tensor operations)



### Basic Operations

`+ - * /`

In [ ]:
# adding values to a tensor

tensor = tf.constant([[1,2],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# Note that the original tensor value doesn't change
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-6, -5],
       [-4, -3]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [ ]:
# tf.somemathoperation(tensor, number) - runs faster on GPU
# for multiplication
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [ ]:
# tensor still remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.add(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

### Matrix Multiplication

In tensorFlow - `tf.matmul(tensor1, tensor2)`

In [ ]:
# matrix multiplication in tensorflow
print(tensor)
print('------------------------------------------------')
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
------------------------------------------------


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
# same done with '@' in python
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
Y = tf.constant([[3,5],[6,7],[1,8]])
XY = tf.matmul(X, Y)
print(X)
print(Y)
print(XY)
print('--------------------------------')
print('Shape of matrix X:', X.shape)
print('Shape of matrix Y:', Y.shape)
print('Shape of matrix XY:', XY.shape)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)
--------------------------------
Shape of matrix X: (3, 3)
Shape of matrix Y: (3, 2)
Shape of matrix XY: (3, 2)


Doing above code with `tf.reshape(tensor, shape=())`

In [ ]:
X = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
Y = tf.constant([3,5,6,7,1,8])
print('Shape of matrix X:', X.shape)
print('Y: ',Y)
print('Shape of matrix Y before reshaping:', Y.shape)
print('But the innermost dimensions must match, and since dimension of matrix X is (3, 3), the shape of matrix B should be (3, 2) since matrix B has 6 elements.')
Y = tf.reshape(Y, shape=(3, 2))
XY = tf.matmul(X, Y)
print('--------------------------------')
print('X: ',X )
print('Y: ',Y)
print('XY: ',XY)
print('--------------------------------')
print('Shape of matrix X:', X.shape)
print('Shape of matrix Y:', Y.shape)
print('Shape of matrix XY:', XY.shape)

Shape of matrix X: (3, 3)
Y:  tf.Tensor([3 5 6 7 1 8], shape=(6,), dtype=int32)
Shape of matrix Y before reshaping: (6,)
But the innermost dimensions must match, and since dimension of matrix X is (3, 3), the shape of matrix B should be (3, 2) since matrix B has 6 elements.
--------------------------------
X:  tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)
Y:  tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)
XY:  tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)
--------------------------------
Shape of matrix X: (3, 3)
Shape of matrix Y: (3, 2)
Shape of matrix XY: (3, 2)


Using `tf.transpose(tensor)` 

In [ ]:
print('Transpose of matrix Y: ',tf.transpose(Y))
print()
print('Matrix X: ', X)
print()
tf.matmul(tf.transpose(Y), X)

Transpose of matrix Y:  tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)

Matrix X:  tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

In [ ]:
# Element wise multiplication when using '*'

tensor, tensor
print('-----------------------------------------------')
tensor*tensor

-----------------------------------------------


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
x = tf.constant([[1,2],[3,4]])
y = tf.ones(shape=(2,2), dtype='int32')
print(x)
print(y)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [ ]:
# axes = 1 in tf.tensordot is equivalent to matrix multiplication
tf.tensordot(x,y,axes=1) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [ ]:
tf.tensordot(x,y,axes=0) # we get a tensor of order 4

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]]]], dtype=int32)>

### Changing the datatype of tensor

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
b = tf.constant([1.7, 7.4])
b, b.dtype 

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
c = tf.constant(3)
c.dtype

tf.int32

In [ ]:
 # changing from float32 to float16 -> reduced precision
d = tf.cast(b, dtype=tf.float16)
d, d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
 # changing from int32 to float32 -> reduced precision
 e = tf.cast(c, dtype=tf.float32)
 e, e.dtype

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>, tf.float32)

### Aggragating tensors

Aggregating tensors = condensing them form multiple values down to a smaller amount of values

In [ ]:
# Getting absolute values
D = tf.constant([-1,-5])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -5], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [ ]:
# Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))  # 50 random values between 0 and 100
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 94, 21, 63, 95,  5, 57, 80, 70, 12, 11,  0, 79, 68, 19, 54, 29,
       34, 88, 55, 31,  4,  6, 24, 72, 11, 47, 46, 35, 24, 76, 46, 74,  5,
       57, 22, 69, 13, 77, 11, 95, 22, 59, 29, 42,  7, 15,  6, 81, 55])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Finding the minimum
tf.reduce_min(E)   # equivalent to np.min() in numpy

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Finding the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [ ]:
# Finding the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# FInding the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2101>

In [ ]:
# Finding variance 
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=847.7396>

In [ ]:
# Finding the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))  # E was int32 initially; float was given in example

# if any type error shown in tensorflow, cast that type to tf.float32

<tf.Tensor: shape=(), dtype=float32, numpy=29.115969>

### Finding the positional maximum and minimum

At which index of the tensor (row) does the maximum value occurs; useful when needed to find index in prediction probability (output of softmax function)

In [ ]:
# creating new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=(50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Finding the positional maximum
tf.argmax(F)  # similar to np.argmax

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Finding max value of tensor F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Sanity check
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Finding positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Sanity check
assert(F[tf.argmin(F)]) == tf.reduce_min(F)

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# creating a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(50,)), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)  # Removes dimensions of size 1 from the shape of a tensor
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot Encoding tensors

In [ ]:
# creating a list of indices
l = [0,1,2,3]

# One Hot Encoding the list of indices
tf.one_hot(l, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(l, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(l, depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [ ]:
# Specifying custom values for one hot encoding
# The locations represented by indices in indices take value on_value,
# while all other locations take value off_value.
tf.one_hot(l, depth=4, on_value='Deep Learning', off_value='NLP' )

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Deep Learning', b'NLP', b'NLP', b'NLP'],
       [b'NLP', b'Deep Learning', b'NLP', b'NLP'],
       [b'NLP', b'NLP', b'Deep Learning', b'NLP'],
       [b'NLP', b'NLP', b'NLP', b'Deep Learning']], dtype=object)>

In [ ]:
l_1 = [0, 1, 2, 1, 4]
tf.one_hot(l_1, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

### Squaring, Log, Square root

Some functions in tf.math

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# finding the square root (will error, method requires non-int type; cast to float32)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# finsing the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensorflow built on tensors and Numpy built on arrays and thus both have good inter-operability

In [ ]:
# creating a tensor directly from numpy array 
J = tf.constant(np.array([1.,2.,3.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
# converting tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
J = tf.constant([1.0, 5.0])
# to access the tensor alone directly
print(J.numpy())
# accessing specific elements in tensor
print(J.numpy()[1])

[1. 5.]
5.0


In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([1.,2.,3.]))
tensor_J = tf.constant([1.,2.,3.])

# checking datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)